### ISSUE TITLE
SpinValueRGB_ValueChanged wywala 3 razy NullReferenceException przy uruchamianiu aplikacji

### ISSUE THREAD

**Issue by Kiel97** [Kiel97/biometrix-wpfix#2]
Najprawdopodobniej Label inicjalizuje się szybciej niż Spinnery i ich wartości

**Comment by adambajguz** [comment]
Zamiast mieć podpięte zdarzenie SpinValueRGB_ValueChanged w XAMLu, podepnij je w C# za pomoca SpinValueRGB.ValueChanged += SpinValueRGB_ValueChange

**Comment by Kiel97** [comment]
To działa! Dzięki za pomoc Adaś :1st_place_medal: 
commit: 156f71701ee639fa2209b0677ceb4a0c8d27d46a
